# Generated by Django 2.0.4 on 2018-04-05 17:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=1000, null=True)),
                ('media_id', models.CharField(max_length=1000, null=True)),
                ('ruta_img', models.CharField(max_length=1000)),
                ('seguirnos', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('hastags', models.CharField(default=None, max_length=1000)),
                ('seguir_otros', models.CharField(default=None, max_length=1000)),
                ('cant_etiqueta', models.IntegerField(default=0)),
                ('like_amigo_otros', models.IntegerField(default=0)),
                ('seguirme_amigos', models.IntegerField(default=0)),
                ('seguir_amigos_otras', models.IntegerField(default=0)),
                ('condiciones', models.TextField(max_length=1000)),
                ('ganadores', models.IntegerField(default=0)),
                ('activo', models.IntegerField(default=0)),
                ('publi_ganadores', models.IntegerField(default=0)),
                ('view_otro', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ganadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_concurso', models.IntegerField(default=0)),
                ('media_id', models.CharField(max_length=1000, null=True)),
                ('username', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=1000)),
                ('imagen', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('seguidores', models.IntegerField(default=0)),
                ('seguidos', models.IntegerField(default=0)),
                ('fotos', models.IntegerField(default=0)),
                ('foto_perfil', models.TextField(default=None, max_length=1000)),
                ('hastags', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=1000)),
                ('talla', models.CharField(max_length=1000, null=True)),
                ('modelo', models.CharField(max_length=1000, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('disponible', models.IntegerField(default=1)),
                ('texto', models.TextField(default=None, max_length=1000)),
                ('descripcion_producto', models.TextField(default=None, max_length=1000)),
                ('res_automatica', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=16, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, max_length=9, null=True)),
                ('user_insta', models.CharField(blank=True, max_length=100, null=True)),
                ('pass_insta', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_modificacion', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=1000)),
                ('cantidad', models.IntegerField(default=0)),
                ('varias', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=10, max_digits=19)),
                ('nombre_cliente', models.CharField(default=None, max_length=100)),
                ('telefono_cliente', models.CharField(default=None, max_length=100)),
                ('descripcion_venta', models.TextField(default=None, max_length=1000)),
                ('fecha_venta', models.DateTimeField(default=datetime.datetime.now)),
                ('id_producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admingo.Productos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios'),
        ),
        migrations.AddField(
            model_name='info',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios'),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios'),
        ),
        migrations.AddField(
            model_name='ganadores',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios'),
        ),
        migrations.AddField(
            model_name='concursos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios'),
        ),
    ]
