# Generated by Django 2.0.1 on 2018-04-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursos',
            name='fin_carga',
            field=models.IntegerField(default=0),
        ),
    ]
