# Generated by Django 2.0.1 on 2018-03-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0002_productos_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='id_producto',
            field=models.CharField(max_length=1000),
        ),
    ]
