# Generated by Django 2.0.1 on 2018-04-28 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0002_concursos_fin_carga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pausas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=1000, null=True)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios')),
            ],
        ),
    ]
