# Generated by Django 2.0.1 on 2018-03-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0003_auto_20180319_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='id_producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admingo.Productos'),
        ),
    ]
