# Generated by Django 2.0.1 on 2018-05-02 00:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0003_pausas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finanzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(default=0)),
                ('media_id', models.CharField(max_length=1000)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=10, max_digits=19)),
                ('nombre_cliente', models.CharField(default=None, max_length=100)),
                ('telefono_cliente', models.CharField(default=None, max_length=100)),
                ('descripcion_finanza', models.TextField(default=None, max_length=1000)),
                ('fecha_venta', models.DateTimeField(default=datetime.datetime.now)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios')),
            ],
        ),
    ]
