# Generated by Django 2.0.1 on 2018-05-02 00:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0004_finanzas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(default=None, max_length=100)),
                ('telefono_cliente', models.CharField(default=None, max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Ventas')),
            ],
        ),
        migrations.RemoveField(
            model_name='finanzas',
            name='fecha_venta',
        ),
        migrations.AddField(
            model_name='finanzas',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
