# Generated by Django 2.0.1 on 2018-05-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0005_auto_20180502_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='id_venta',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
