# Generated by Django 2.0.1 on 2018-05-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0006_auto_20180502_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='id_producto',
            field=models.IntegerField(default=0),
        ),
    ]
