# Generated by Django 2.0.1 on 2018-05-05 21:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0007_auto_20180504_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=1000)),
                ('nombre', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Productos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=1000)),
                ('nombre', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Productos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios')),
            ],
        ),
    ]
