# Generated by Django 2.0.1 on 2018-05-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0008_modelos_tallas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='talla',
            field=models.IntegerField(default=-1),
        ),
    ]
