# Generated by Django 2.0.1 on 2018-05-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0009_auto_20180508_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelos',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='modelos',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='modelos',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='tallas',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='tallas',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='tallas',
            name='media_id',
        ),
        migrations.AlterField(
            model_name='productos',
            name='modelo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='talla',
            field=models.IntegerField(default=0),
        ),
    ]
