# Generated by Django 2.0.1 on 2018-05-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0010_auto_20180508_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelos',
            name='id_producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admingo.Productos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelos',
            name='id_usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelos',
            name='media_id',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tallas',
            name='id_producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admingo.Productos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tallas',
            name='id_usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admingo.Usuarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tallas',
            name='media_id',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
