# Generated by Django 2.0.1 on 2018-05-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0012_auto_20180510_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='tallas',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
