# Generated by Django 2.0.1 on 2018-05-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0013_auto_20180510_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='talla',
        ),
    ]
