# Generated by Django 2.0.5 on 2018-06-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0015_usuarios_fin_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='cambiar_pass_insta',
            field=models.IntegerField(default=0),
        ),
    ]
