# Generated by Django 2.0.3 on 2019-09-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0016_usuarios_cambiar_pass_insta'),
        ('admingo', '0004_auto_20180319_1940'),
    ]

    operations = [
    ]
