# Generated by Django 2.0.3 on 2020-02-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admingo', '0017_merge_20190919_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finanzas',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='modelos',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='modelos',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='pausas',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='tallas',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='tallas',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='concursos',
            name='fin_carga',
        ),
        migrations.AddField(
            model_name='productos',
            name='modelo',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='talla',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cambiar_pass_insta',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fin_registro',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Finanzas',
        ),
        migrations.DeleteModel(
            name='Modelos',
        ),
        migrations.DeleteModel(
            name='Pausas',
        ),
        migrations.DeleteModel(
            name='Tallas',
        ),
    ]
